// <auto-generated />
namespace SymCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _13_init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_13_init));
        
        string IMigrationMetadata.Id
        {
            get { return "201912231730342_1.3_init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
