// <auto-generated />
namespace SymCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class commentControlPage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(commentControlPage));
        
        string IMigrationMetadata.Id
        {
            get { return "202001151014272_commentControlPage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
